// This file is needed because it is used by vscode and other tools that
// call `jest` directly.  However, unless you are doing anything special
// do not edit this file

const standard = require('@grafana/toolkit/src/config/jest.plugin.config');

// This process will use the same config that `yarn test` is using
config = standard.jestConfig();
config.setupFilesAfterEnv = ['<rootDir>/config/setupTests.ts'];

config.globalSetup = '<rootDir>/config/globalSetup.ts';

module.exports = config;
